repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/cpplint/cpplint
    rev: master
    hooks:
      - id: cpplint
        name: Run cpplint on C++ files
        entry: cpplint
        language: python
        files: \.(cpp|h|hpp|cc|cxx)$
        types: [file]

  - repo: local
    hooks:
      - id: clang-format
        name: Run clang-format on C++ files
        entry: clang-format -i
        language: system
        types: [c++, c]
        files: \.(cpp|h|hpp|cc|cxx)$
