# Name of the workflow (shows up in GitHub Actions UI)
name: CI Pipeline

# Trigger workflow when pushing to main branch
on:
  push:
    branches: [ main ]

jobs:
  # --------------------------------------------
  # 🔒 Security Check Job
  # --------------------------------------------
  security-checks:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Pulls repo code into the runner

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2  # Scans repo for hardcoded secrets
        with:
          args: "--verbose"

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main  # Another secrets scanner
        with:
          scanArguments: "--only-verified"

  # --------------------------------------------
  # 🧹 Linting Job (Python with Ruff)
  # --------------------------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4  # Setup Python 3.x environment
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: pip install ruff  # Python linter

      - name: Run Ruff
        run: ruff . || true  # Lint entire repo, don’t fail build if it finds issues

  # --------------------------------------------
  # 🐳 Docker Build and Push to GHCR
  # --------------------------------------------
  docker-build-push:
    runs-on: ubuntu-latest
    needs: [security-checks, lint]  # Only run after security & lint jobs pass
    permissions:
      contents: read       # Allow access to repo code
      packages: write      # Allow pushing to GitHub Container Registry

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Enables multi-platform builds

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3  # Auth to GHCR with GitHub token
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Your GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # Auto-generated GitHub token

      - name: Build and push Docker image (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .  # Build context is root of repo
          push: true  # Push the image to GHCR
          platforms: linux/amd64  # Force build for amd64 (compatible with kind cluster)
          tags: ghcr.io/notrllykav/cpp-docker-app:latest  # Tag for GHCR
          provenance: false  # Disable attestation-only builds (fixes manifest issues)
