name: CI Pipeline

# Trigger workflow on push to main and pull requests targeting main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --------------------------------------------
  # 🔒 Security Check Job
  # --------------------------------------------
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--verbose"

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: "--only-verified"

  # --------------------------------------------
  # 🧹 Linting Job (Python with Ruff)
  # --------------------------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff . || true  # Lint entire repo; continue even if lint fails

  # --------------------------------------------
  # ✅ Pre-commit Hook Checks
  # --------------------------------------------
  precommit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  # --------------------------------------------
  # 🐳 Docker Build and Push to GHCR
  # --------------------------------------------
  docker-build-push:
    runs-on: ubuntu-latest
    needs: [security-checks, lint, precommit-checks]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/notrllykav/cpp-docker-app:latest
          provenance: false  # Required to avoid manifest mismatch
